apiVersion: v1
kind: ConfigMap
metadata:
  name: opscenter-middleware-config
  namespace: opscenter
data:
  MW_ENABLED: "true"
  MW_LEADER_ENABLED: "false"
  MQ_ENABLED: "false"
  KAFKA_ENABLED: "false"
  MONGO_ENABLED: "false"
  NACOS_ENABLED: "false"
  MINIO_ENABLED: "false"
  KAFKA_BOOTSTRAP: "kafka.middleware.svc.cluster.local:9092"
  NACOS_URL: "http://nacos.middleware.svc.cluster.local:8848"
  MINIO_ENDPOINT: "minio.middleware.svc.cluster.local:9000"
  ZOOKEEPER_HOSTS: "zookeeper.middleware.svc.cluster.local:2181"
  SSH_KNOWN_HOSTS_FILE: "/opt/opscenter/frontend/ssh_known_hosts"
  CORS_ORIGINS: ""
