<template>
  <div class="view db-view">
    <div class="view-head"><div><h1 class="view-title">数据库</h1><div class="view-sub">实例发现、连接接入、数据库与账号管理</div></div><div class="actions"><button class="btn" :disabled="busy" @click="discover">自动发现</button><button class="btn btn-primary" @click="openForm()">添加实例</button></div></div>
    <div class="layout">
      <aside class="card instances">
        <div class="instance-head"><strong>实例</strong><button class="btn btn-sm" @click="loadInstances">刷新</button></div>
        <button v-for="item in instances" :key="item.id" class="instance" :class="{active:selected?.id===item.id}" @click="choose(item)"><span class="engine">{{ engineLabel(item.engine) }}</span><span class="instance-main"><b>{{ item.name }}</b><small>{{ item.host }}:{{ item.port }}</small></span><i class="status" :class="item.status"></i></button>
        <div v-if="!instances.length&&!busy" class="empty compact">当前主机暂无数据库实例</div>
      </aside>
      <main class="card workspace">
        <div v-if="!selected" class="empty"><div class="empty-icon">▱</div>选择或添加数据库实例</div>
        <template v-else>
          <div class="instance-title"><div><h2>{{ selected.name }}</h2><span class="tag">{{ engineLabel(selected.engine) }}</span><span class="tag" :class="statusTag(selected.status)">{{ statusLabel(selected.status) }}</span><span class="muted">{{ selected.connection_mode }} · {{ selected.has_credentials?'已保存凭证':'待接入' }}</span></div><div class="actions"><button class="btn" @click="testConnection">测试连接</button><button class="btn" @click="openForm(selected)">编辑</button><button class="btn btn-danger" @click="removeInstance">删除配置</button></div></div>
          <div v-if="selected.last_error" class="error-box">{{ selected.last_error }}</div>
          <div class="tabs"><button v-for="tab in availableTabs" :key="tab.key" :class="{active:activeTab===tab.key}" @click="activeTab=tab.key;loadTab()">{{ tab.label }}</button></div>
          <div v-if="tabLoading" class="loading"><span class="spinner"></span>正在读取数据库信息…</div>
          <template v-else-if="activeTab==='overview'">
            <div class="overview-grid"><div class="stat"><span>版本</span><b>{{ overview.version||selected.version||'-' }}</b></div><div class="stat"><span>状态</span><b>{{ statusLabel(selected.status) }}</b></div><div v-if="selected.engine==='redis'" class="stat"><span>内存</span><b>{{ fmtBytes(overview.used_memory) }}</b></div><div v-if="selected.engine==='redis'" class="stat"><span>客户端</span><b>{{ overview.connected_clients??'-' }}</b></div></div>
            <section v-if="selected.engine==='redis'" class="sub"><h3>Keyspace 汇总</h3><pre>{{ JSON.stringify(overview.keyspace||{},null,2) }}</pre></section>
          </template>
          <template v-else-if="activeTab==='databases'">
            <div class="toolbar"><strong>数据库列表</strong><button class="btn btn-primary btn-sm" @click="createDatabase">创建数据库</button></div>
            <table class="table"><thead><tr><th>名称</th><th>所有者</th><th>操作</th></tr></thead><tbody><tr v-for="db in databases" :key="db.name"><td>{{ db.name }}</td><td>{{ db.owner||'-' }}</td><td><button class="btn btn-sm btn-danger" @click="dropDatabase(db)">删除</button></td></tr></tbody></table>
          </template>
          <template v-else>
            <div class="toolbar"><strong>账号列表</strong><button class="btn btn-primary btn-sm" @click="createAccount">创建账号</button></div>
            <table class="table"><thead><tr><th>账号</th><th>来源主机</th><th>权限</th><th>操作</th></tr></thead><tbody><tr v-for="account in accounts" :key="account.username+'@'+account.host"><td>{{ account.username }}</td><td>{{ account.host||'-' }}</td><td>{{ account.superuser?'超级用户':(account.can_login===false?'禁止登录':'普通账号') }}</td><td><button class="btn btn-sm" @click="adjustPermissions(account)">调整权限</button><button class="btn btn-sm" @click="resetPassword(account)">重置密码</button><button class="btn btn-sm btn-danger" @click="removeAccount(account)">删除</button></td></tr></tbody></table>
          </template>
        </template>
      </main>
    </div>

    <div v-if="formOpen" class="modal-mask" @click.self="formOpen=false"><form class="card modal" @submit.prevent="saveInstance"><div class="modal-head"><h3>{{ form.id?'编辑':'添加' }}数据库实例</h3><button type="button" class="btn btn-ghost" @click="formOpen=false">关闭</button></div><div class="form-grid"><div class="field"><label>实例名称</label><input v-model="form.name" class="input" required></div><div class="field"><label>引擎</label><select v-model="form.engine" class="select" :disabled="!!form.id"><option value="mysql">MySQL</option><option value="mariadb">MariaDB</option><option value="postgresql">PostgreSQL</option><option value="redis">Redis</option></select></div><div class="field"><label>连接方式</label><select v-model="form.connection_mode" class="select"><option value="direct">直接连接</option><option value="ssh">SSH 临时隧道</option><option value="docker">容器经 SSH 隧道</option></select></div><div class="field"><label>地址</label><input v-model="form.host" class="input" required placeholder="127.0.0.1"></div><div class="field"><label>端口</label><input v-model.number="form.port" class="input" type="number" min="1" max="65535" required></div><div class="field"><label>用户名</label><input v-model="form.username" class="input"></div><div class="field"><label>密码</label><input v-model="form.password" class="input" type="password" :placeholder="form.id?'留空保留原凭证':'可稍后接入'"></div><div class="field"><label>默认数据库</label><input v-model="form.default_database" class="input"></div></div><div class="modal-foot"><button type="button" class="btn" @click="formOpen=false">取消</button><button class="btn btn-primary" :disabled="busy">保存</button></div></form></div>
  </div>
</template>

<script setup>
import { computed, onMounted, onUnmounted, reactive, ref, watch } from 'vue'
import { api, fmtBytes, toast } from '../api'
import { useHostContext } from '../hostContext'
const {selectedHostId,refreshHosts}=useHostContext();const instances=ref([]),selected=ref(null),activeTab=ref('overview'),overview=ref({}),databases=ref([]),accounts=ref([]),busy=ref(false),tabLoading=ref(false),formOpen=ref(false);let controller=null
const form=reactive({id:'',name:'',engine:'mysql',connection_mode:'direct',host:'127.0.0.1',port:3306,username:'',password:'',default_database:''})
const availableTabs=computed(()=>selected.value?.engine==='redis'?[{key:'overview',label:'运行概览'}]:[{key:'overview',label:'实例概览'},{key:'databases',label:'数据库'},{key:'accounts',label:'账号与权限'}])
function engineLabel(e){return ({mysql:'MySQL',mariadb:'MariaDB',postgresql:'PostgreSQL',redis:'Redis'})[e]||e}function statusLabel(s){return ({online:'在线',error:'异常',pending:'待接入'})[s]||s}function statusTag(s){return s==='online'?'tag-green':s==='error'?'tag-red':'tag-amber'}
async function loadInstances(){if(!selectedHostId.value)return;controller?.abort();controller=new AbortController();busy.value=true;try{instances.value=await api.get('/databases/instances',{server_id:selectedHostId.value},{signal:controller.signal});if(selected.value){selected.value=instances.value.find(x=>x.id===selected.value.id)||null}if(!selected.value&&instances.value.length)choose(instances.value[0])}catch(e){if(e.name!=='AbortError')toast(e.message,'err')}finally{busy.value=false}}
function choose(item){selected.value=item;activeTab.value='overview';loadTab()}
async function loadTab(){if(!selected.value)return;tabLoading.value=true;try{if(activeTab.value==='overview')overview.value=await api.get(`/databases/instances/${selected.value.id}/overview`);if(activeTab.value==='databases')databases.value=await api.get(`/databases/instances/${selected.value.id}/databases`);if(activeTab.value==='accounts')accounts.value=await api.get(`/databases/instances/${selected.value.id}/accounts`)}catch(e){toast(e.message,'err')}finally{tabLoading.value=false}}
function openForm(item=null){Object.assign(form,item?{...item,password:''}:{id:'',name:'',engine:'mysql',connection_mode:'direct',host:'127.0.0.1',port:3306,username:'',password:'',default_database:''});formOpen.value=true}
async function saveInstance(){busy.value=true;try{const payload={name:form.name,host:form.host,port:form.port,username:form.username,password:form.password||undefined,default_database:form.default_database,connection_mode:form.connection_mode};if(form.id)await api.put(`/databases/instances/${form.id}`,payload);else await api.post('/databases/instances',{...payload,server_id:selectedHostId.value,engine:form.engine});formOpen.value=false;await loadInstances();toast('实例已保存','ok')}catch(e){toast(e.message,'err')}finally{busy.value=false}}
async function discover(){busy.value=true;try{const data=await api.post('/databases/discover',null,{signal:controller?.signal});toast(`发现完成，新增 ${data.added} 个实例`,'ok');await loadInstances()}catch(e){toast(e.message,'err')}finally{busy.value=false}}
async function testConnection(){try{const data=await api.post(`/databases/instances/${selected.value.id}/test`);toast(`连接成功 · ${data.version}`,'ok');await loadInstances()}catch(e){toast(e.message,'err');await loadInstances()}}
async function removeInstance(){const name=prompt(`输入实例名称“${selected.value.name}”确认删除配置；不会删除数据库本身`);if(name!==selected.value.name)return;await api.del(`/databases/instances/${selected.value.id}`,{query:{confirm_name:name}});selected.value=null;toast('实例配置已删除','ok');loadInstances()}
async function createDatabase(){const name=prompt('数据库名称');if(!name)return;try{await api.post(`/databases/instances/${selected.value.id}/databases`,{name});toast('数据库已创建','ok');loadTab()}catch(e){toast(e.message,'err')}}
async function dropDatabase(db){if(prompt(`输入数据库名称“${db.name}”确认永久删除`)!==db.name)return;try{await api.del(`/databases/instances/${selected.value.id}/databases/${encodeURIComponent(db.name)}`);toast('数据库已删除','ok');loadTab()}catch(e){toast(e.message,'err')}}
async function createAccount(){const username=prompt('账号名称');if(!username)return;const password=prompt('初始密码');if(!password)return;try{await api.post(`/databases/instances/${selected.value.id}/accounts`,{username,password,databases:[]});toast('账号已创建','ok');loadTab()}catch(e){toast(e.message,'err')}}
async function resetPassword(account){const password=prompt(`为 ${account.username} 设置新密码`);if(!password)return;try{await api.put(`/databases/instances/${selected.value.id}/accounts/${encodeURIComponent(account.username)}`,{password});toast('密码已重置','ok')}catch(e){toast(e.message,'err')}}
async function adjustPermissions(account){const value=prompt(`输入 ${account.username} 可管理的数据库，多个名称用逗号分隔；留空表示撤销全部数据库权限`);if(value===null)return;const names=value.split(',').map(x=>x.trim()).filter(Boolean);try{await api.put(`/databases/instances/${selected.value.id}/accounts/${encodeURIComponent(account.username)}`,{databases:names});toast('账号权限已更新','ok')}catch(e){toast(e.message,'err')}}
async function removeAccount(account){if(!confirm(`确认删除数据库账号 ${account.username}？`))return;try{await api.del(`/databases/instances/${selected.value.id}/accounts/${encodeURIComponent(account.username)}`);toast('账号已删除','ok');loadTab()}catch(e){toast(e.message,'err')}}
watch(selectedHostId,()=>{selected.value=null;instances.value=[];loadInstances()});watch(()=>form.engine,e=>{if(!form.id)form.port=({mysql:3306,mariadb:3306,postgresql:5432,redis:6379})[e]});onMounted(async()=>{await refreshHosts();loadInstances()});onUnmounted(()=>controller?.abort())
</script>

<style scoped>.actions{display:flex;gap:8px;align-items:center}.layout{display:grid;grid-template-columns:270px minmax(0,1fr);gap:14px;min-height:620px}.instances{padding:8px}.instance-head{display:flex;justify-content:space-between;align-items:center;padding:5px 6px 10px}.instance{width:100%;border:0;background:transparent;display:flex;align-items:center;gap:9px;padding:10px;border-radius:8px;text-align:left;cursor:pointer;color:var(--text)}.instance:hover,.instance.active{background:#eff6ff}.engine{width:38px;height:38px;border-radius:8px;background:#dbeafe;color:#1d4ed8;display:flex;align-items:center;justify-content:center;font-size:10px;font-weight:700}.instance-main{display:flex;flex-direction:column;gap:3px;min-width:0;flex:1}.instance-main small{color:var(--muted);overflow:hidden;text-overflow:ellipsis}.status{width:8px;height:8px;border-radius:50%;background:#f59e0b}.status.online{background:var(--ok)}.status.error{background:var(--err)}.compact{padding:30px 8px}.workspace{min-width:0}.instance-title{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;border-bottom:1px solid var(--border);padding-bottom:14px}.instance-title h2{display:inline-block;margin:0 10px 8px 0;font-size:20px}.instance-title .tag,.instance-title .muted{margin-right:7px}.tabs{display:flex;gap:18px;border-bottom:1px solid var(--border);margin:14px 0}.tabs button{border:0;background:transparent;padding:10px 4px;cursor:pointer;color:var(--muted)}.tabs button.active{color:var(--brand);border-bottom:2px solid var(--brand)}.overview-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.stat{background:#f8fafc;padding:16px;border-radius:8px}.stat span{display:block;color:var(--muted);font-size:12px;margin-bottom:8px}.stat b{font-size:17px}.toolbar{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}.sub{margin-top:20px}.sub pre{background:#0f172a;color:#dbeafe;padding:14px;border-radius:8px}.error-box{background:#fef2f2;color:var(--err);padding:10px;border-radius:8px;margin-top:12px}.modal-mask{position:fixed;inset:0;background:rgba(15,23,42,.5);z-index:2000;display:flex;align-items:center;justify-content:center}.modal{width:min(680px,92vw)}.modal-head,.modal-foot{display:flex;justify-content:space-between;align-items:center}.modal-head h3{margin:0}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 14px;margin-top:18px}.modal-foot{justify-content:flex-end;gap:8px}@media(max-width:900px){.layout{grid-template-columns:1fr}.instances{max-height:280px;overflow:auto}.overview-grid{grid-template-columns:1fr 1fr}}
</style>
