<template>
  <div class="view">
    <div class="view-head"><div><h1 class="view-title">进程管理</h1><div class="view-sub">查看进程资源、网络连接，并安全发送系统信号</div></div><button class="btn" :disabled="loading" @click="load">刷新</button></div>
    <div class="card filters"><input v-model="filters.search" class="input" placeholder="搜索 PID、命令或用户" @keyup.enter="load"><input v-model="filters.user" class="input" placeholder="用户"><select v-model="filters.state" class="select"><option value="">全部状态</option><option value="R">运行</option><option value="S">休眠</option><option value="D">等待</option><option value="Z">僵尸</option></select><select v-model="filters.sort" class="select"><option value="cpu">CPU 排序</option><option value="memory">内存排序</option></select><button class="btn btn-primary" @click="load">筛选</button></div>
    <div v-if="error" class="error-box">{{ error }}</div>
    <section class="card table-wrap"><div class="table-meta">共 {{ rows.length }} 项 · {{ source }} · {{ time }}</div><table class="table"><thead><tr><th>PID</th><th>名称</th><th>用户</th><th>状态</th><th>CPU</th><th>内存</th><th>RSS</th><th>操作</th></tr></thead><tbody><tr v-for="row in rows" :key="row.pid"><td class="mono">{{ row.pid }}</td><td>{{ row.command || row.name }}</td><td>{{ row.user }}</td><td>{{ row.state }}</td><td>{{ row.cpu_percent }}%</td><td>{{ row.memory_percent }}%</td><td>{{ fmtBytes(row.rss_bytes) }}</td><td><button class="btn btn-sm" @click="showDetail(row)">详情</button><button class="btn btn-sm btn-danger" @click="sendSignal(row,'TERM')">结束</button><button class="btn btn-sm btn-danger" @click="sendSignal(row,'KILL')">强制结束</button></td></tr></tbody></table><div v-if="loading" class="loading"><span class="spinner"></span>加载中</div><div v-else-if="!rows.length" class="empty">暂无匹配进程</div></section>
    <div v-if="detail" class="modal-mask" @click.self="detail=null"><div class="card modal"><div class="modal-head"><h3>进程 {{ detail.pid }}</h3><button class="btn btn-ghost" @click="detail=null">关闭</button></div><p class="mono detail-line">{{ detail.summary }}</p><h4>网络连接</h4><pre>{{ detail.network_connections?.join('\n') || '无网络连接' }}</pre></div></div>
  </div>
</template>
<script setup>
import { onMounted, onUnmounted, reactive, ref, watch } from 'vue'
import { api, fmtBytes, toast } from '../api'
import { useHostContext } from '../hostContext'
const {selectedHostId,refreshHosts}=useHostContext();const rows=ref([]),loading=ref(false),error=ref(''),source=ref(''),time=ref('-'),detail=ref(null);const filters=reactive({search:'',user:'',state:'',sort:'cpu'});let controller=null
async function load(){if(!selectedHostId.value)return;controller?.abort();controller=new AbortController();loading.value=true;error.value='';try{const data=await api.get(`/servers/${selectedHostId.value}/processes`,{...filters,limit:300},{signal:controller.signal});rows.value=data.items||data.processes||[];source.value=data.source||'-';time.value=data.timestamp?new Date(data.timestamp*1000).toLocaleTimeString():'-'}catch(e){if(e.name!=='AbortError')error.value=e.message}finally{loading.value=false}}
async function showDetail(row){try{detail.value=await api.get(`/servers/${selectedHostId.value}/processes/${row.pid}`)}catch(e){toast(e.message,'err')}}
async function sendSignal(row,signal){const label=signal==='KILL'?'强制结束':'结束';if(!confirm(`确认${label}进程 ${row.pid}（${row.command||row.name}）？`))return;try{await api.post(`/servers/${selectedHostId.value}/processes/${row.pid}/signal`,{signal});toast('操作已发送','ok');load()}catch(e){toast(e.message,'err')}}
watch(selectedHostId,load);onMounted(async()=>{await refreshHosts();load()});onUnmounted(()=>controller?.abort())
</script>
<style scoped>.filters{display:grid;grid-template-columns:2fr 1fr 150px 150px auto;gap:10px;margin-bottom:14px}.table-wrap{padding:0;overflow:auto}.table-meta{padding:12px 16px;color:var(--muted);font-size:12px}.table td:last-child{white-space:nowrap}.table td:last-child .btn{margin-right:5px}.error-box{padding:12px;background:#fef2f2;color:var(--err);border-radius:8px;margin-bottom:12px}.modal-mask{position:fixed;inset:0;background:rgba(15,23,42,.5);z-index:2000;display:flex;align-items:center;justify-content:center}.modal{width:min(760px,90vw);max-height:80vh;overflow:auto}.modal-head{display:flex;justify-content:space-between;align-items:center}.modal-head h3{margin:0}.detail-line{white-space:pre-wrap}.modal pre{background:#0f172a;color:#dbeafe;padding:14px;border-radius:8px;white-space:pre-wrap}@media(max-width:900px){.filters{grid-template-columns:1fr 1fr}}</style>
